// console.log("Hello " + "World") // "Hello World"
// console.log("The sum of 2 and 3 is " + (2 + 3)) // "The sum of 2 and 3 is 5"
//"Not recommended" to use string concatenation with + operator because it can lead to confusion and unintended consequences.
//  It is better to use template literals for string interpolation for clarity and maintainability. 
// String concatenation : it is the process of combining two or more strings into a single string. In JavaScript, you can use the + operator to concatenate strings. For example:


// string interpolation : it is a way to embed expressions inside string literals, 
// allowing you to create dynamic strings that can include variables and expressions.
//  In JavaScript, you can use template literals (enclosed in backticks ``) to achieve string interpolation. For example:

// we are creating placeholders. this is modern way to write syntax.


let name = "Rushikesh"
let age = 28
let message = `My name is ${name} and I am ${age} years old.`
// console.log(message) // "My name is Rushikesh and I am 28 years old."
// console.log(` Name: ${name}, How Old : ${age}`) // " Name: Rushikesh, How Old : 28"


// second method to write a string.

const gameName = new String('Chess')
// console.log(gameName) // [String: 'Chess']
// console.log(gameName.toUpperCase()) // "CHESS"
// console.log(gameName.length) // 5
// console.log(gameName[3])
// console.log(gameName.substring(0, 2)) // "Ch"
// console.log(gameName.__proto__) // String.prototype : it is an object that contains all the methods and properties that are available to string instances in JavaScript. When you create a string using either string literal syntax or the String constructor, it inherits from String.prototype, which means it has access to all the methods defined on String.prototype. For example, when you call gameName.toUpperCase(), it looks for the toUpperCase method on the gameName instance, and if it doesn't find it there, it looks for it on String.prototype, where it finds the method and executes it. This is how inheritance works in JavaScript, and it allows us to use built-in methods on string instances without having to define them ourselves.
// console.log(gameName.charAt(2)) // "e"
// console.log(gameName.indexOf("e")) // 2

const gameName2 = gameName.substring(0, 3) // "Che"
//console.log(gameName2) // "Che" value you will get less than one from last number.

const gameName3 = gameName.slice(-4,5)
console.log(gameName3)

// //trim
// const gameName4 = "   Chess   "
// console.log(gameName4) // "   Chess   "
// console.log(gameName4.trim())
// console.log(gameName4.trimStart()) // "Chess   "
// console.log(gameName4.trimEnd()) // "   Chess"

// replace: it is used to replace a specified value with another value in a string. For example:

// const gameName6 ="https://www.rushikesh%20G.com"
// console.log(gameName6.replace("%20", "-")) // "https://www.rushikesh-G.com" : it replaces the first occurrence of "%20" with "-". If there are multiple occurrences of "%20", only the first one will be replaced. To replace all occurrences, you can use a regular expression with the global flag (g) like this: gameName6.replace(/%20/g, "-")

// // includes: it is used to check if a string contains a specified value. It returns true if the string contains the value, and false otherwise. For example:
// const gameName7 = "Chess is a popular board game."
// console.log(gameName7.includes("Chess")) // true
// console.log(gameName7.includes("Checkers")) // false

// // bold : it is used to create a string that represents bold text. For example:
// const gameName8 = "Chess"
// console.log(gameName8.bold()) // "<b>Chess</b>" : it returns a string that represents the original string wrapped in HTML <b> tags, which can be used to display the text in bold when rendered in a web page. However, it is important to note that the bold() method is not commonly used in modern JavaScript development, and it is generally recommended to use CSS for styling text instead of relying on HTML tags generated by JavaScript methods.

//Match method to create a string
console.log ( gameName.match("s")) // it returns an iterator of all matches of the regular expression "s" in the string "Chess". Each match is represented as an array containing the matched substring and its index in the original string. In this case, it will return an iterator that yields two matches: ["s", 2] and ["s", 4], indicating that the letter "s" appears at index 2 and index 4 in the string "Chess". You can use a loop or the spread operator to convert the iterator into an array if you want to access all the matches at once. For example: [...gameName.matchAll("s")] will return [["s", 2], ["s", 4]].

// normalize : it is used to normalize a string to a specific Unicode normalization form. This can be useful for comparing strings that may have different representations but are considered equivalent in terms of their content. For example:
const str1 = "café"
const str2 = "cafe\u0301" // "e" followed by a combining acute accent
console.log(str1 === str2) // false : because str1 and str2 have different Unicode representations, even though they look the same when rendered.
console.log(str1.normalize() === str2.normalize()) // true : because normalize() converts both strings to the same Unicode normalization form, allowing for a proper comparison of their content.

// PadStart and PadEnd : they are used to pad a string with a specified character until it reaches a certain length. For example:
const str3 = "5"
console.log(str3.padStart(3, "0")) // "005" : it pads the string "5" with "0" at the start until it reaches a length of 3.
console.log(str3.padEnd(3, "0")) // "500" : it pads the string "5" with "0" at the end until it reaches a length of 3.

//